spring:
  application:
    name: ead-course-service
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:postgresql://localhost:5432/course
    username: postgres
    password: mysecretpassword
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
  rabbitmq:
    addresses: amqps://vsofjkut:WWJY_EeQVli0IQadxcv_YwBOqQcSsxv9@stingray.rmq.cloudamqp.com/vsofjkut

server:
  compression:
    enabled: true
  port: 8181
  servlet:
    context-path: /ead-course
  forward-headers-strategy: framework

ead:
  api:
    url:
      auth-user: "http://ead-auth-user-service/auth-user"
  broker:
    exchange:
      user-event: ead.userevent
    queue:
      user-event-queue:
        name: ead.userevent.ms.course